---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        description: prevents giant files from being committed.
        args: [--maxkb=1024]
      - id: mixed-line-ending
        description: replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: trailing-whitespace
        description: trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: detect-private-key
        description: detects the presence of private keys.
        exclude: .gitleaks.toml
      - id: check-merge-conflict
        description: checks for files that contain merge conflict strings.
      - id: fix-byte-order-marker
        description: removes utf-8 byte order marker.
      - id: check-case-conflict
        description: |
          checks for files that would conflict in case-insensitive filesystems.
      - id: check-executables-have-shebangs
        description: ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable
        description: |
          ensures that (non-binary) files with a shebang are executable
      - id: check-symlinks
        description: checks for symlinks which do not point to anything.
      - id: destroyed-symlinks
        description: |
          detects symlinks which are changed to regular files with a content of
          a path which that symlink was pointing to.
      - id: end-of-file-fixer
        description: |
          ensures that a file is either empty, or ends with one newline.
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: .*docker-compose.*|.*gitlab-ci.*
        args: [--allow-multiple-documents]
  # pre-commit install --install-hooks
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
        name: Ensure commit messages follow Conventional Commit spec
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        language_version: system
        name: Lint markdown Documents
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shfmt
        name: Check shell style with shfmt
      - id: shellcheck
        name: Shell scripts conform to shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker
        exclude: CHANGELOG.md
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.0
    hooks:
      - id: gitleaks
        description: Detect hardcoded secrets using Gitleaks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        description: Lint git commit messages.
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        exclude: .*docker-compose.*|.*gitlab-ci.yml
        args: [--mapping, '2', --sequence, '4', --offset, '2']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        exclude: .*docker-compose.*|.*gitlab-ci.yml
        args: [--format, parsable, --strict]
